#!/bin/bash

clear

echo "🖥"
echo "My setup, by @sebacarrasco93"
echo ""

old_git_email=$(git config --global user.email)
old_git_name=$(git config --global user.name)

echo "1/4: Enter your Git email ($old_git_email)"
read git_email

git_email="${git_email:-$old_git_email}"

echo "2/4: Enter your Git name ($old_git_name)"
read git_name

git_name="${git_name:-$old_git_name}"

echo "$git_name $git_email"

echo "3/4: Enter your SSH identificator for this PC: Example: My Work Mac"
read ssh_identificator

echo "4/4: Generating SSH key with ed25519"
ssh-keygen -t ed25519 -C "$ssh_identificator"

echo "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Add links to Homebrew"
echo >> /Users/seba/.zprofile
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/seba/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"

echo "Installing formulaes"
brew install git fish node pnpm htop nvim vim mailpit

echo "Starting mailpit"
brew services start mailpit

echo "Configuring Git"
git config --global init.defaultBranch main
git config --global user.email "$git_email"
git config --global user.name "$git_name"

echo "Installing casks"
brew install --cask --force telegram google-chrome herd visual-studio-code dbngin raycast iterm2 whatsapp macs-fan-control shottr nrlquaker-winbox sequel-ace tableplus warp postman spotify firefox vlc keka wireshark insomnia monitorcontrol microsoft-edge arduino-ide hot cameracontroller youtube-downloader omnidisksweeper android-file-transfer android-file-transfer imageoptim tiles 4k-video-downloaderplus brave-browser speedtest-cli

echo "Installing MS Office Apps"
brew install --cask --force microsoft-word microsoft-excel microsoft-powerpoint

echo "Installing fonts"
brew install --cask --force homebrew/cask-fonts/font-cascadia-code homebrew/cask-fonts/font-jetbrains-mono-nerd-font homebrew/cask-fonts/font-fira-code-nerd-font

echo "Downloading Dvorak Spanish"
curl -Lo ~/Library/Keyboard\ Layouts/Dvorak-Spanish.bundle.zip https://github.com/sebacarrasco93/my-setup/raw/main/extra/Dvorak-Spanish.bundle.zip

echo "Unzip Dvorak Spanish"
unzip -o ~/Library/Keyboard\ Layouts/Dvorak-Spanish.bundle.zip -d ~/Library/Keyboard\ Layouts/

echo "Removing Dvorak Zip file"
rm ~/Library/Keyboard\ Layouts/Dvorak-Spanish.bundle.zip

echo "Finding fish shell location"
set fish_path=$(command -v fish)

echo "Checking if fish shell is correctly installed in order to prevent errors"
if [ -n "$fish_path" ]; then
    eval "echo $fish_path | sudo tee -a /etc/shells"
    eval "chsh -s $fish_path"
fi

curl https://raw.githubusercontent.com/sebacarrasco93/my-setup/main/macOS-fish | fish
